name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set CI env (SQLite)
        run: |
          echo "FLASK_APP=app.wsgi:app" >> $GITHUB_ENV
          echo "FLASK_DEBUG=0" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret" >> $GITHUB_ENV
          echo "SQLALCHEMY_DATABASE_URI=sqlite:///test.db" >> $GITHUB_ENV

      # If your tests require tables, create them. This avoids needing 'flask db upgrade' in CI.
      - name: Prepare DB (create tables)
        run: |
          python - <<'PY'
          import os
          os.environ.setdefault("FLASK_APP","app.wsgi:app")
          os.environ.setdefault("SQLALCHEMY_DATABASE_URI","sqlite:///test.db")
          from app.wsgi import app
          from app.extensions import db
          with app.app_context():
              db.create_all()
              print("SQLite tables created for tests.")
          PY

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests with coverage
        run: pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing
