name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set testing env
        run: |
          echo "FLASK_APP=app.wsgi:app" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret" >> $GITHUB_ENV
          echo "SQLALCHEMY_DATABASE_URI=sqlite:///test.db" >> $GITHUB_ENV
          echo "WTF_CSRF_ENABLED=0" >> $GITHUB_ENV
          echo "RUN_DB_MIGRATIONS=0" >> $GITHUB_ENV

      - name: Prepare DB (create tables)
        run: |
          python - <<'PY'
          import os
          os.environ.setdefault("FLASK_APP","app.wsgi:app")
          os.environ.setdefault("SQLALCHEMY_DATABASE_URI","sqlite:///test.db")
          os.environ.setdefault("WTF_CSRF_ENABLED","0")
          os.environ.setdefault("RUN_DB_MIGRATIONS","0")
          from app.wsgi import app
          from app.extensions import db
          with app.app_context():
              db.create_all()
          PY

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
